### PR TITLE
Add Visual Studio project and solution

### PR DESCRIPTION
**Pull request by boflynn**
To make it easier to work on, adding a basic Visual Studio solution and project file.  I'm using Visual Studio 2017, so there might be settings in it that might not work with previous versions.  If this doesn't work with your version, let me know and it can probably be downgraded.

### CODE REVIEW

**Comment by mastalock** [comment]
I actually do have .csproj and .sln files for it, which have a few more settings from working on it, including an icon installed and version numbers and who knows what else I fiddled with... I'd rather upload those, if that works for you. Trick is.... how do I do that?

**Comment by mastalock** [comment]
To clarify "how do I do that," I mean like the github way. I can see where I can just add the files to the main branch and merge right away. But what is the intended practice, making use of a branch and pull request and all that, I've never done that. I see that somehow connected with this comment thread, your files are attached, but I can't see where I can update/overwrite them or add there, only at the master branch view. And if I try to add the files here, it acts like I want to embed them in my comment, says it won't accept .sln files, needs .pdf or .jpg, so I think this is the wrong place.

**Comment by boflynn** [comment]
If you're using the Github for Windows tool, you should be able to click on the commit, then click the little monitor icon to open a file in it.  But if you've already got a functional sln/csproj that's got my stuff and more, I can just go ahead and close this PR and wait until you get yours merged in.  Nothing special about this and saves you from having to deal with the ugly merge of the two sets of files.

**Comment by mastalock** [comment]
Ok, then it sounds like there is actually not an option of editing/overwriting your non-committed files before committing, there is simply closing the PR branch, is that the idea? I'm using the Github website btw,  but I was able to access most of the same stuff you were talking about after you said to open the commit, which I hadn't thought to do before now. Once I was in there, I could see your requested added files in the familiar directory, and it even had the upload files button, but it was grayed out.

So I'll go ahead and close this, then upload mine. Thanks for the advice, and feel free to check it out now that they're up!

**Comment by boflynn** [comment]
One small issue, the new solution file is referencing the csproj as being in a subdirectory called Seizmojigger, so it wants the folder structure to be:

- root \ Seizmojigger.sln
- root \ Seizmojigger \ Seizmojigger.csproj
- root \ Seizmojigger \ Program.cs

**Comment by mastalock** [comment]
Yeah, that is how I have it on my computer. Becaaaauuuse, I'm an idiot? Couldn't figure my way through a VS setup the first time maybe? Yeah that's what happened, in the New Project wizard process, I didn't realize that making a project would make a folder named after the project, and I thought I would be spewing all the Seizmo contents into the main VS folder. So I made the Seizmo sub folder very first thing, just in case I had more than one VS project in my future, only to realize later "Oh, VS made me a Seizmo folder, and THAT is the root already... so I didn't need to do that. Whatever." I will try rearranging the hierarchy from within VS, and maybe it will just fix it.

**Comment by boflynn** [comment]
Nah, I would say that the project organization on your computer is correct, but you need to get it reflected on GitHub.  TBH, I'm not sure how to create folders through the web UI, just through the desktop/CLI stuff.

For reference, you'll usually want to have that subfolder structure because you'll rarely have just one project in your solution.  Even in this case, I can see this solution ending up something like:

- Seizmojigger.ConsoleApplication
- Seizmojigger.Library
- Seizmojigger.Tests

**Comment by boflynn** [comment]
Just figured out how to make folders through the UI:

1. Open the file, e.g. [the project file](https://github.com/mastalock/seizmojigger/blob/master/Seizmojigger.csproj)
2. Click the pencil/edit button
3. The name of the file is now a textbox; add the folder name then a forward slash, e.g. Seizmojigger/Seizmojigger.csproj, and the UI will realize there's a new folder
4. Click Commit Changes

**Comment by mastalock** [comment]
Got it! Should I add like.... aaalll of my VS files (bin, obj, Properties, all contents) into there too with the same folder structure?

**Comment by boflynn** [comment]
bin and obj are compiled artifacts, so should not be put into source control.  In fact, GitHub should (hopefully) exclude them because they're specified in the .gitignore file, which tells git which files you don't want committed for this exact reason (and others).

Properties and the other contents, e.g. *.cs, *.jpg, etc, definitely add.  Looking at the csproj file, you're missing at least:

- App.config
- Properties\AssemblyInfo.cs
- seizmo.ico

All of these, along with Program.cs, will need to be put into the Seizmojigger sub-folder.

**Pull request closed without merging**
